//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNTWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
        }
    
        public int SanPhamID { get; set; }
        public string MaSo { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public int GiaBan { get; set; }
        public Nullable<int> NhaCungCapID { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> LoaiID { get; set; }
        public string ChatLieu { get; set; }
        public string MauSac { get; set; }
        public string Hinh { get; set; }
        public bool HetHang { get; set; }
        public string BiDanh { get; set; }
        public Nullable<int> star { get; set; }
        public string ListHinh { get; set; }
        public Nullable<int> GiamGia { get; set; }
    
        public virtual Loai Loai { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
    }
}
